// Angular/angular-app/src/employee-table/employee-table.component.ts
import { Component, SimpleChanges } from '@angular/core';
import { Employee } from './Models/employee';
import {FormsModule} from '@angular/forms';


@Component({
  selector: 'app-employee-table',
  imports: [FormsModule],
  templateUrl: './employee-table.component.html',
  styleUrl: './employee-table.component.css'
})
export class EmployeeTableComponent {
  employees:Employee[]=[];
  pageNumber:number=1;
  pageSize:number=2;
  totalCount:number=0;
  totalPages:number=0;
  searchText:string="";
  paginateArray:number[]=[];
  createEmployeeFormData:Employee=new Employee;
  updateEmployeeFlag:boolean=false;
  updateEmployeeId:number=-1;
  updateEmployeeFormData:Employee=new Employee;

  ngOnInit(){
    this.fetchData();
    
  }

  ngOnChange(pageNumber: SimpleChanges){
  
  }
  async fetchData(){
    let url=`https://localhost:7149/api/Employees?pageNumber=${this.pageNumber}&pageSize=${this.pageSize}`;
    if(this.searchText !==""){
     url=`https://localhost:7149/api/Employees?pageNumber=${this.pageNumber}&pageSize=${this.pageSize}&searchText=${this.searchText}`;
    }
    let response=await fetch(url);
    let paginatedData= await response.json();

   this.employees=paginatedData.employees;
   this.totalCount=paginatedData.totalCount;
   this.totalPages=paginatedData.totalPages;

   this.paginateArray=[];
   for(let i=1;i<=paginatedData.totalPages;i++)
   {
    this.paginateArray.push(i);
   }
   
  }

  handlePagination(page:number){
    this.pageNumber=page;
    this.fetchData();
  }

  async createEmployee(){
    let options={
      "method":"POST",
      "headers":{
        "content-Type": "application/json"
      },
      "body":JSON.stringify(this.createEmployeeFormData)
    };

    await fetch(`https://localhost:7149/api/Employees`,options);
    this.pageNumber=this.totalPages;
    if(this.totalCount+1 > this.pageNumber *this.pageSize)
    {
      this.pageNumber++;
    }
    await this.fetchData();
    this.createEmployeeFormData.name="";
    this.createEmployeeFormData.email="";
    this.createEmployeeFormData.salary=0;

  }

  async deleteEmployee(employeeId:number)
  {
    let options={
      "method":"DELETE",
      
    }
    let response=await fetch(`https://localhost:7149/api/Employees/${employeeId}`,options);
    if(this.totalCount -1 ==(this.pageNumber-1)*this.pageSize && this.pageNumber!=1){
      this.pageNumber--;
    }
    
    await this.fetchData();
    
  }

 async updateEmployee(){
    let options={
      "method":"PUT",
      "headers":{
        "Content-Type":"application/json"
      },
      "body":JSON.stringify(this.updateEmployeeFormData)
    }
    let response=await fetch(`https://localhost:7149/api/Employees/${this.updateEmployeeId}`,options);
    await this.fetchData();
    this.updateEmployeeFlag=false;
    this.updateEmployeeId=-1;
    this.updateEmployeeFormData.name="";
    this.updateEmployeeFormData.email="";
    this.updateEmployeeFormData.salary=0;
 }

 addUpdateForm(employee:Employee){
  this.updateEmployeeFlag=true;
  this.updateEmployeeId=employee.employeeId;
  this.updateEmployeeFormData.name=employee.name;
  this.updateEmployeeFormData.email=employee.email;
  this.updateEmployeeFormData.salary=employee.salary;

 }

}

<p>Employee Details</p>


<form (submit)="createEmployee()" >
    Enter Name:<input type="text" name="name" [(ngModel)]="createEmployeeFormData.name"><br>
    Enter Email:<input type="email" name="email" [(ngModel)]="createEmployeeFormData.email"><br>
    Enter Salary:<input type="number" name="salary" [(ngModel)]="createEmployeeFormData.salary" ><br>

    <input type="submit" value="Add"/>
</form>
<table>
    <tr>
        <th>Employee Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Salary</th>
        <th>Actions</th>
    </tr>
    @for(employee of employees; track employee.employeeId)
    
    {
        @if(updateEmployeeFlag && employee.employeeId ==updateEmployeeId)
        {
        <tr>
            <td>{{employee.employeeId}}</td>
            <td><input type="text" [(ngModel)]="updateEmployeeFormData.name"/></td>
            <td><input type="email" [(ngModel)]="updateEmployeeFormData.email"/></td>
            <td><input type="number" [(ngModel)]="updateEmployeeFormData.salary"/></td>
            <td>
                <button (click)="updateEmployee()">Update</button>
                <button (click)="deleteEmployee(employee.employeeId)">Delete</button>
            </td>
        </tr>
        }
    @else{
        <tr>
            <td>{{employee.employeeId}}</td>
            <td>{{employee.name}}</td>
            <td>{{employee.email}}</td>
            <td>{{employee.salary}}</td>
            <td>
                <button (click)="addUpdateForm(employee)">Update</button>
                <button (click)="deleteEmployee(employee.employeeId)">Delete</button>
            </td>
        </tr>

    }
    }
</table>
<div>
    @for(page of paginateArray; track page)
    {
        <button (click)="handlePagination(page)">{{page}}</button>
    }
</div>

// ReactJs/first-react-app/src/Components/EmployeeTable.jsx
import React, { useEffect, useState } from 'react'

const EmployeeTable = () => {

    const [employeeList, setEmployeeList] = useState([]);
    const [pageNumber, setPageNumber] = useState(1);
    const [pageSize, setPageSize] = useState(2);
    const [totalCount, setTotalCount] = useState(0);
    const [totalPages, setTotalPages] = useState(0);
    const [createEmployeeFormData, setCreateEmployeeFormData] = useState({
        "name": "",
        "email": "",
        "salary": 0
    });
    const [updateEmployeeFormData, setUpdateEmployeeFormData] = useState({
        "name": "",
        "email": "",
        "salary": 0
    });
    const [updateEmployeeFlag, setUpdateEmployeeFlag] = useState(false);
    const [updateEmployeeId, setUpdateEmployeeId] = useState(-1);

    useEffect(() => {
        fetchData();
    }, [])

    useEffect(() => {
        fetchData();
    }, [pageNumber])


    async function fetchData() {
        let response = await fetch(`https://localhost:7149/api/Employees?pageNumber=${pageNumber}&pageSize=${pageSize}`);
        let paginatedData = await response.json();
        setEmployeeList(paginatedData.employees);
        setTotalCount(paginatedData.totalCount);
        setTotalPages(paginatedData.totalPages);
        console.log(employeeList);
    }

    let paginationArray = []
    for(let i = 1; i <= totalPages; i++){
        paginationArray.push(i);
    }


    async function handleSubmit(e){
        e.preventDefault();
        let options = {
            "method": "POST",
            "headers": {
                "Content-Type": "application/json"
            },
            "body": JSON.stringify(createEmployeeFormData)
        };
        
        await fetch("https://localhost:7149/api/Employees", options);

        await fetchData();

        setPageNumber(totalPages);

        setCreateEmployeeFormData({
            "name": "",
            "email": "",
            "salary": 0
        })
    }

    function handleChange(e){
        setCreateEmployeeFormData({...createEmployeeFormData, [e.target.name] : e.target.value})
    }

    function handleUpdatedChange(e){
        setUpdateEmployeeFormData({...updateEmployeeFormData, [e.target.name]: e.target.value})
    }

    async function handleUpdate(){
        let options = {
            "method": "PUT",
            "headers": {
                "Content-Type": "application/json"
            },
            "body": JSON.stringify(updateEmployeeFormData)
        };
        
        await fetch(`https://localhost:7149/api/Employees/${updateEmployeeId}`, options);

        await fetchData();

        setUpdateEmployeeFlag(false);

        setUpdateEmployeeId(-1);

        setUpdateEmployeeFormData({
            "name": "",
            "email": "",
            "salary": 0
        })
    }

    

    async function deleteEmployee(employeeId){
        await fetch(`https://localhost:7149/api/Employees/${employeeId}`, {
            "method": "DELETE"
        });
        let tc = totalCount - 1;
        let tp = Math.ceil(tc / pageSize);
        if(pageNumber == totalPages && tp != totalPages){
            setPageNumber(tp);
        }
        await fetchData();
    }


    return (
        <div>
            <form onSubmit={handleSubmit}>
                <input type="text" name='name' placeholder='Enter name' value={createEmployeeFormData.name} onChange={handleChange} /><br />
                <input type="email" name='email' placeholder='Enter Email' value={createEmployeeFormData.email} onChange={handleChange}/><br />
                <input type="number" name='salary' placeholder='Enter Salary' value={createEmployeeFormData.salary} onChange={handleChange}/><br />
                <input type="submit" value="Add Employee" />
            </form>
            <table border={1}> 
                <tr>
                    <th>Employee Id</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Salary</th>
                    <th>Actions</th>
                </tr>
                {
                    employeeList.map((employee) => {
                        let condition = updateEmployeeFlag && updateEmployeeId == employee.employeeId;
                        if(condition){
                            return (
                                <tr>
                                    <td>{employee.employeeId}</td>
                                    <td><input type="text" name='name' value={updateEmployeeFormData.name} onChange={handleUpdatedChange}/></td>
                                    <td><input type="email" name='email' value={updateEmployeeFormData.email} onChange={handleUpdatedChange}/></td>
                                    <td><input type="number" name='salary' value={updateEmployeeFormData.salary} onChange={handleUpdatedChange}/></td>
                                    <td>
                                        <button onClick={handleUpdate}>Update</button>
                                        <button onClick={() => {
                                            deleteEmployee(employee.employeeId);
                                        }}>Delete</button>
                                    </td>
                                </tr>
                            )
                        }
                        return (
                            <tr>
                                <td>{employee.employeeId}</td>
                                <td>{employee.name}</td>
                                <td>{employee.email}</td>
                                <td>{employee.salary}</td>
                                <td>
                                    <button onClick={() => {
                                        setUpdateEmployeeFlag(true);
                                        setUpdateEmployeeId(employee.employeeId);
                                        setUpdateEmployeeFormData({
                                            "name": employee.name,
                                            "email": employee.email,
                                            "salary": employee.salary
                                        })
                                    }}>Update</button>
                                    <button onClick={() => {
                                        deleteEmployee(employee.employeeId);
                                    }}>Delete</button>
                                </td>
                            </tr>
                        )
                    //     return (
                    //         <tr>
                    //             <td>{employee.employeeId}</td>
                    //             {
                    //                 condition 
                    //                     ?   <td>
                    //                             <input 
                    //                                 type="text" 
                    //                                 name='name' 
                    //                                 value={updateEmployeeFormData.name} 
                    //                                 onChange={handleUpdatedChange}
                    //                             />
                    //                         </td> 
                    //                     :   <td>{employee.name}</td>
                    //             }
                    //             {
                    //                 condition 
                    //                     ? <td><input type="email" name='email' value={updateEmployeeFormData.email} onChange={handleUpdatedChange}/></td>
                    //                     : <td>{employee.email}</td>
                    //             }
                    //             {
                    //                 condition 
                    //                     ? <td><input type="number" name='salary' value={updateEmployeeFormData.salary} onChange={handleUpdatedChange}/></td>
                    //                     : <td>{employee.salary}</td>
                    //             }                            
                    //             <td>
                    //                 {
                    //                     condition 
                    //                         ? <button onClick={handleUpdate}>Update</button>
                    //                         : <button onClick={() => {
                    //                                 setUpdateEmployeeFlag(true);
                    //                                 setUpdateEmployeeId(employee.employeeId);
                    //                                 setUpdateEmployeeFormData({
                    //                                     "name": employee.name,
                    //                                     "email": employee.email,
                    //                                     "salary": employee.salary
                    //                                 })
                    //                             }}>Update</button>
                    //                 }
                                    
                    //                 <button onClick={() => {
                    //                     deleteEmployee(employee.employeeId);
                    //                 }}>Delete</button>
                    //             </td>
                    //         </tr>
                    //     )
                     })
                }
            </table>
            <div>
                {
                    paginationArray.map((num) => {
                        return (
                            <button style={{"backgroundColor" : (pageNumber==num) ? "green" : "grey" }} onClick={() => {
                                setPageNumber(num);
                            }}>{num}</button>
                        )
                    })
                }
            </div>
        </div>
    )
}

export default EmployeeTable
